<?php
// examination/includes/sbe_datesheet_pdf.php
// Pure-PHP (no library) PDF builder + datesheet publishing for SBE Mid/Final exams.

if (!function_exists('_sbe_pdf_escape')) {
    function _sbe_pdf_escape($s) {
        $s = is_string($s) ? $s : (string) $s;
        $s = trim(preg_replace('/\s+/', ' ', $s));
        $converted = @iconv('UTF-8', 'Windows-1252//TRANSLIT//IGNORE', $s);
        if ($converted !== false) {
            $s = $converted;
        } else {
            $s = preg_replace('/[^\x20-\x7E]/', '?', $s);
        }
        $s = str_replace('\\', '\\\\', $s);
        $s = str_replace('(', '\\(', $s);
        $s = str_replace(')', '\\)', $s);
        return $s;
    }
}

if (!function_exists('_sbe_pdf_fit')) {
    function _sbe_pdf_fit($s, $maxW, $fs) {
        $s = trim(preg_replace('/\s+/', ' ', (string) $s));
        $cpw = max(1.0, $fs * 0.5);
        $len = mb_strlen($s);
        $w = 0.0;
        for ($i = 0; $i < $len; $i++) {
            if ($w + $cpw > $maxW) {
                if ($i <= 1) {
                    return _sbe_pdf_escape($s);
                }
                return _sbe_pdf_escape(rtrim(mb_substr($s, 0, $i)) . '...');
            }
            $w += $cpw;
        }
        return _sbe_pdf_escape($s);
    }
}

/**
 * Build a minimal, valid A4 PDF containing the given exam schedule rows.
 *
 * @param array  $rows     Each row: exam_code, title, exam_type, section, exam_date, start_time, end_time, location, invigilators
 * @param string $title    Datesheet title
 * @param string $subtitle Optional subtitle line
 * @return string PDF binary
 */
function sbe_datesheet_pdf(array $rows, string $title, string $subtitle = ''): string {
    $pageW = 595.28; // A4 width (pt)
    $pageH = 841.89; // A4 height (pt)
    $mL = 40;
    $mR = 40;
    $mT = 48;
    $mB = 42;

    $cols = [
        ['label' => '#',            'x' => 0,   'w' => 22],
        ['label' => 'Exam Code',    'x' => 22,  'w' => 66],
        ['label' => 'Exam Title',   'x' => 88,  'w' => 105],
        ['label' => 'Type',         'x' => 193, 'w' => 34],
        ['label' => 'Date',         'x' => 227, 'w' => 58],
        ['label' => 'Time',         'x' => 285, 'w' => 62],
        ['label' => 'Sec',          'x' => 347, 'w' => 24],
        ['label' => 'Location',     'x' => 371, 'w' => 74],
        ['label' => 'Invigilators', 'x' => 445, 'w' => 70.28],
    ];

    $fsTitle = 13;
    $fsSub = 9;
    $fsHead = 8.5;
    $fsRow = 8.5;
    $rowH = 15;

    $pages = [];
    $page = [];
    $y = 0;

    $newPage = function () use (&$pages, &$page, &$y, $pageH, $mT, $title, $subtitle, $fsTitle, $fsSub, $fsHead, $mL, $mR, $pageW, $cols) {
        if (!empty($page)) {
            $pages[] = $page;
        }
        $page = [];
        $y = $pageH - $mT;

        $page[] = "BT /F2 {$fsTitle} Tf {$mL} {$y} Td (" . _sbe_pdf_escape($title) . ") Tj ET";
        $y -= 17;
        if ($subtitle !== '') {
            $page[] = "BT /F1 {$fsSub} Tf {$mL} {$y} Td (" . _sbe_pdf_escape($subtitle) . ") Tj ET";
            $y -= 13;
        }
        $page[] = "BT /F1 7 Tf {$mL} {$y} Td (Generated by University MIS - Examination Department) Tj ET";
        $y -= 15;

        foreach ($cols as $c) {
            $page[] = "BT /F2 {$fsHead} Tf " . ($mL + $c['x']) . " {$y} Td (" . _sbe_pdf_escape($c['label']) . ") Tj ET";
        }
        $page[] = "{$mL} " . ($y - 3) . " m " . ($pageW - $mR) . " " . ($y - 3) . " l S";
        $y -= 15;
    };

    $newPage();

    $num = 0;
    foreach ($rows as $r) {
        if ($y < $mB + $rowH) {
            $newPage();
        }
        $num++;
        $startT = (string) ($r['start_time'] ?? '');
        $endT = (string) ($r['end_time'] ?? '');
        if (strlen($startT) >= 5) { $startT = substr($startT, 0, 5); }
        if (strlen($endT) >= 5) { $endT = substr($endT, 0, 5); }
        $dateStr = (string) ($r['exam_date'] ?? '');
        $dateDisplay = $dateStr !== '' ? date('d M Y', strtotime($dateStr)) : '';

        $vals = [
            (string) $num,
            (string) ($r['exam_code'] ?? ''),
            (string) ($r['title'] ?? ''),
            (string) ($r['exam_type'] ?? ''),
            $dateDisplay,
            $startT . ' - ' . $endT,
            (string) ($r['section'] ?? ''),
            (string) ($r['location'] ?? ''),
            (string) ($r['invigilators'] ?? ''),
        ];

        foreach ($cols as $ci => $c) {
            $txt = _sbe_pdf_fit($vals[$ci], $c['w'] - 4, $fsRow);
            $page[] = "BT /F1 {$fsRow} Tf " . ($mL + $c['x'] + 2) . " {$y} Td (" . $txt . ") Tj ET";
        }
        $y -= $rowH;
    }

    if (!empty($page)) {
        $pages[] = $page;
    }

    $N = count($pages);
    $nCatalog = 1;
    $nPages = 2;
    $nF1 = 3 + 2 * $N;
    $nF2 = $nF1 + 1;

    $objects = [];
    $objects[$nCatalog] = "<< /Type /Catalog /Pages {$nPages} 0 R >>";

    $kids = [];
    for ($i = 0; $i < $N; $i++) { $kids[] = (string) (3 + $i) . ' 0 R'; }
    $objects[$nPages] = "<< /Type /Pages /Kids [ " . implode(' ', $kids) . " ] /Count {$N} >>";

    for ($i = 0; $i < $N; $i++) {
        $nPage = 3 + $i;
        $nCont = 3 + $N + $i;
        $objects[$nPage] = "<< /Type /Page /Parent {$nPages} 0 R /MediaBox [0 0 {$pageW} {$pageH}] "
            . "/Resources << /Font << /F1 {$nF1} 0 R /F2 {$nF2} 0 R >> >> /Contents {$nCont} 0 R >>";
    }

    for ($i = 0; $i < $N; $i++) {
        $nCont = 3 + $N + $i;
        $ops = $pages[$i];
        $ops[] = "BT /F1 7 Tf {$mL} " . ($mB - 8) . " Td (Page " . ($i + 1) . " of {$N}) Tj ET";
        $stream = implode("\n", $ops) . "\n";
        $objects[$nCont] = "<< /Length " . strlen($stream) . " >>\nstream\n" . $stream . "endstream";
    }

    $objects[$nF1] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>";
    $objects[$nF2] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>";

    ksort($objects);
    $pdf = "%PDF-1.4\n";
    $offsets = [];
    foreach ($objects as $num => $body) {
        $offsets[$num] = strlen($pdf);
        $pdf .= "{$num} 0 obj\n{$body}\nendobj\n";
    }
    $xrefPos = strlen($pdf);
    $count = max(array_keys($objects)) + 1;
    $pdf .= "xref\n0 {$count}\n0000000000 65535 f \n";
    for ($i = 1; $i < $count; $i++) {
        $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
    }
    $pdf .= "trailer\n<< /Size {$count} /Root {$nCatalog} 0 R >>\nstartxref\n{$xrefPos}\n%%EOF\n";

    return $pdf;
}

/**
 * Regenerate (or create) the published datesheet for a semester + exam type and
 * upsert it into sbe_datesheets so it shows up in the Datesheets submodule.
 */
function sbe_regenerate_datesheet($conn, $semesterId, $departmentId, $examType) {
    if (!$conn) { return; }
    $semesterId = (int) $semesterId;
    $departmentId = $departmentId ? (int) $departmentId : 0;
    $examType = ($examType === 'Mid' || $examType === 'Final') ? $examType : '';
    if ($semesterId <= 0 || $examType === '') { return; }

    $rows = [];
    $sql = "SELECT e.exam_code, e.title, e.exam_type, es.section, es.exam_date, es.start_time, es.end_time, es.location,
                   (SELECT GROUP_CONCAT(t.teacher_name ORDER BY t.teacher_name SEPARATOR ', ')
                    FROM sbe_exam_invigilators inv JOIN teachers t ON t.teacher_id = inv.teacher_id
                    WHERE inv.schedule_id = es.schedule_id) AS invigilators
            FROM sbe_exam_schedule es
            JOIN sbe_exams e ON e.exam_id = es.exam_id
            WHERE es.semester_id = ? AND e.exam_type = ? AND es.status != 'Cancelled'
            ORDER BY es.exam_date ASC, es.start_time ASC";
    $stmt = $conn->prepare($sql);
    if (!$stmt) { return; }
    $stmt->bind_param('is', $semesterId, $examType);
    $stmt->execute();
    $res = $stmt->get_result();
    while ($r = $res->fetch_assoc()) { $rows[] = $r; }
    $stmt->close();

    if (empty($rows)) { return; }

    $semName = '';
    $deptName = '';
    $stmt = $conn->prepare("SELECT sem.semester_name, d.department_name
                            FROM semesters sem
                            LEFT JOIN departments d ON d.department_id = sem.department_id
                            WHERE sem.semester_id = ?");
    if ($stmt) {
        $stmt->bind_param('i', $semesterId);
        $stmt->execute();
        $meta = $stmt->get_result()->fetch_assoc();
        if ($meta) {
            $semName = (string) ($meta['semester_name'] ?? '');
            $deptName = (string) ($meta['department_name'] ?? '');
        }
        $stmt->close();
    }

    $title = trim(($semName !== '' ? $semName . ' - ' : '')
        . ($examType === 'Mid' ? 'Mid Term' : 'Final Term')
        . ' Exam Datesheet');
    $subtitle = $deptName !== '' ? 'Department of ' . $deptName : '';

    $pdf = sbe_datesheet_pdf($rows, $title, $subtitle);

    $uploadDir = $_SERVER['DOCUMENT_ROOT'] . '/uni-mis-project/uploads/datesheets/';
    if (!is_dir($uploadDir)) {
        @mkdir($uploadDir, 0777, true);
    }
    $fileName = 'sbe_' . strtolower($examType) . '_sem' . $semesterId . '_' . date('Ymd_His') . '.pdf';
    $filePath = 'uploads/datesheets/' . $fileName;

    if (file_put_contents($uploadDir . $fileName, $pdf) === false) { return; }

    $old = null;
    $stmt = $conn->prepare("SELECT datesheet_id, file_path FROM sbe_datesheets
                            WHERE semester_id = ? AND exam_type = ? ORDER BY datesheet_id DESC LIMIT 1");
    if ($stmt) {
        $stmt->bind_param('is', $semesterId, $examType);
        $stmt->execute();
        $old = $stmt->get_result()->fetch_assoc();
        $stmt->close();
    }

    $userId = (int) ($_SESSION['user_id'] ?? 0);

    if ($old) {
        $oldId = (int) $old['datesheet_id'];
        $upd = $conn->prepare("UPDATE sbe_datesheets SET title = ?, department_id = ?, file_name = ?, file_path = ?, uploaded_by = ? WHERE datesheet_id = ?");
        if ($upd) {
            $upd->bind_param('sisssi', $title, $departmentId, $fileName, $filePath, $userId, $oldId);
            $upd->execute();
            $upd->close();
        }
        if (!empty($old['file_path'])) {
            $oldFile = $uploadDir . basename((string) $old['file_path']);
            if (is_file($oldFile)) { @unlink($oldFile); }
        }
    } else {
        $ins = $conn->prepare("INSERT INTO sbe_datesheets (title, department_id, semester_id, exam_type, file_name, file_path, uploaded_by)
                               VALUES (?, ?, ?, ?, ?, ?, ?)");
        if ($ins) {
            $ins->bind_param('sissssi', $title, $departmentId, $semesterId, $examType, $fileName, $filePath, $userId);
            $ins->execute();
            $ins->close();
        }
    }
}
